name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go build -v ./...

      - run: >
          go tool ginkgo -r
          --github-output
          --race
          --trace
          --randomize-all
          --coverprofile=cover.out
          --skip-package=ghfs

      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: cover.out

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31.9.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go tool gomod2nix
      - run: git diff --exit-code gomod2nix.toml

  ghfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: ghfs/go.mod
          cache-dependency-path: ghfs/go.sum

      - run: go build -v ./ghfs/...

      - run: >
          go -C ghfs tool ginkgo -r
          --github-output
          --race
          --trace
          --randomize-all
          --coverprofile=cover.out

      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: ghfs/cover.out
